sources:
  - name: core
    schema: core
    tables: 
      - name: condition
      - name: encounter
      - name: location
      - name: medication
      - name: patient
      - name: practitioner
      - name: procedure
      - name: medical_claim